### ISSUE TITLE
What does the size of a variable mean?

### ISSUE THREAD

**Issue by Oliver-zrz** [jluttine/junction-tree#16]
Hello,
I have no idea what the size of the variable below represents
```
{
    var1: size1,
    ...
    varM: sizeM
}
```
But I found that it can have an effect on the result， could you please explain what it means?

**Comment by dar326** [comment]
Hello,
The size is the number of discrete states which a variable can possibly take on.

**Comment by Oliver-zrz** [comment]
> Hello, The size is the number of discrete states which a variable can possibly take on.

I understand, thanks a lot
